### ISSUE TITLE
CSS 404

### ISSUE THREAD

**Issue by Gusbenz** [grinnellplans/grinnellplans-php#278]
Ugh, I posted in the Rails version first. I'm confused as what one is official. 

Anyway, my girlfriend is a Grinnell alum and she's having issues with the CSS 404ing

http://veronicaerb.com/plans/eversosimple.css is no longer.

**Comment by acohn** [comment]
Third party stylesheets are created and hosted by individual Plans users, not by Plans itself, so you would have to talk to Veronica Erb (the author of that stylesheet) to see if she moved it somewhere else you can get to. Or explore veronicaerb.com and see if you can find it?

Unofficially, I also use a slightly modified version of that stylesheet, with a little different display of autoread lists and secrets. It's at https://css.alexcohn.com/eversosimple.css - maybe that will work for her?

**Comment by Gusbenz** [comment]
Alex,

Thanks! I had no idea you could customize the style within Plans, since I'm not the one who uses it. But your comment helped me figure it out. Thanks. She's a happy camper now.
