### ISSUE TITLE
Registration error preventing me from successfully creating account - Captcha

### ISSUE THREAD

**Issue by CarterMarkegard** [grinnellplans/grinnellplans-php#297]
Username: [guest]
Revision: 8df2de4
URL: www.grinnellplans.com/register.php
User-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Safari/537.36

How can we reproduce the problem?
1. Try to register for grinnell plans via a mobile browser (I tried chrome and samsung's proprietary browser).
2. Fill out the registration form with student data (and answer the captcha puzzle)
3. Hit the "Register" button

What is the expected output? What do you see instead?
 I expect to be redirected to a password and user account creation page, but instead the same registration page loads without form data and a message that recaptcha didn't work(even though it was passed). This is a cool webapp, I hope the dev/maintenence squad is still active.

**Comment by acohn** [comment]
Fixed, but will take a bit for the fix to take effect.

I forgot to include "www.grinnellplans.com" as an allowed source hostname in the reCaptcha config. If you'd hit the same page without the www, it works fine. I've added the www hostname to the allowed list but it doesn't seem to have taken effect yet.

For now, please register at [https://grinnellplans.com/register.php](https://grinnellplans.com/register.php). Once I see that you've been able to register successfully, I'll close this issue.

Sorry for the inconvenience, and thanks for your interest in Plans.

**Comment by acohn** [comment]
Fix committed in 1609bcc4. I see that Carter was able to register successfully. Closing.
